### PR TITLE
Enable https

### PR DESCRIPTION
**Pull request by thuyihan1206**
Change http to https due to new github.io HTTPS enforcement.

### CODE REVIEW

**Comment by ychaikin** [comment]
@thuyihan1206 Is HTTPS enforcement enabled by default? I can see reach my sites through regular HTTP.

**Comment by kalmanh** [comment]
Heroku doesn't care if you are coming in through http or https. I can certainly enable https enforcement through Rails (where all requests sent to http will be rerouted to https).

http://api.rubyonrails.org/classes/ActionController/ForceSSL/ClassMethods.html#method-i-force_ssl

**Comment by ychaikin** [comment]
@kalmanh I don't think that's necessary. GitHub started with HTTPS enforcement, but I don't think it's on by default. I could be wrong. Haven't tried it on a new repo. However, on my existing repos, regular HTTP is working just fine. 

Students often default their own URL with httpS and then it's giving them trouble. One solution is to tell them to switch the hard-coded URLs to HTTPS. However, if this is not necessary, it's better they figure that out and just change their URL of how they access their GitHub deployments.

**Comment by Fayadh56** [comment]
@ychaikin Yup, it's not necessary. Although, for newer repositories with gh-pages it's automatically set as the default I believe.

**Comment by ychaikin** [comment]
@Fayadh56 @thuyihan1206 Ah! Just tested it. Not only is it on by default, but I don't see a way to turn it off unless you have your own custom domain... In that case, I am merging this pull request. That change is, in fact, necessary.

**Comment by Fayadh56** [comment]
@ychaikin Oh the more you know!

**Comment by thuyihan1206** [comment]
It appears that GitHub has enforced HTTPS for all new GitHub pages with a
github.io domain created after June 15, 2016.

https://help.github.com/articles/securing-your-github-pages-site-with-https/

And I believe some browser, such as Google Chrome, doesn't allow requesting
an insecure XMLHttpRequest from an HTTPS page, thus I send this pull
request.

Kalman's suggestion would work for Rails applications. However, none of the
examples in this course is Rails specific. :-(

Evan



--
Evan (Chi Pang) Chan
chchan1206@gmail.com

**Pull request merged**
