### PR TITLE
MyOnlineMeal.com

### PR DESCRIPTION
**Pull request by mdasad5396**
This is myOnlineMeal.com Website In this website i use HTML&CSS.

Are you trying to provide an assignment solution?

If yes, this is NOT the place to do it. Do NOT create Pull Requests to this repository unless you find an error in the code or description of something and want to suggest a change. If you want to suggest a change, create an issue first to see if we are in agreement that such a change should be made.

Again, DO NOT create pull requests to this repository to submit your assignment solutions. Follow the instructions in the course on how to submit your assignment. If confused about that, ask on the course's forum.

### CODE REVIEW

**Comment by MrKataPlease** [comment]
I already had someone send me an email about this. That pull request was
unintentional.

**Comment by mdasad5396** [comment]
file:///A:/resturant%20site/index.html

**Comment by MrKataPlease** [comment]
Got it.

**Comment by MrKataPlease** [comment]
I actually don't know what's going on. I've never even looked at your my meal thing. I'm sorry. It's happened somewhere else too. If you know how to make this stop, please tell me.

**Comment by ychaikin** [comment]
@mdasad5396 Stop creating Pull Requests to this repository. If you don't stop, I'll be forced to block you from it completely.

**Pull request closed without merging**
